extern crate cbindgen;

use std::env;

fn main() {
    let Ok(crate_dir) = env::var("CARGO_MANIFEST_DIR") else {
        // Fallback or exit gracefully
        println!("cargo:warning=CARGO_MANIFEST_DIR is not set");
        return;
    };

    // Re-run build if source files change
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/parser.rs");
    println!("cargo:rerun-if-changed=src/proto.rs");

    // Generate C header
    match cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("USBREDIRPARSER_H")
        .with_autogen_warning("/* Generated by cbindgen - DO NOT EDIT */")
        .with_namespaces::<String>(&[])
        .with_parse_deps(true)
        .with_parse_include(&["usbredirparser-rs"])
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file("include/usbredirparser.h");
        }
        Err(e) => {
            println!("cargo:warning=Unable to generate bindings: {e}");
        }
    }
}
