extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // Re-run build if source files change
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/parser.rs");
    println!("cargo:rerun-if-changed=src/proto.rs");

    // Generate C header
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("USBREDIRPARSER_H")
        .with_autogen_warning("/* Generated by cbindgen - DO NOT EDIT */")
        // internal helper modules like 'proto' or 'parser' shouldn't be namespaced in C
        .with_namespaces::<String>(&[])
        .with_parse_deps(true)
        .with_parse_include(&["usbredir-safe"]) // Parse this crate
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/usbredirparser.h");
}
